version: '3'
services:
  grafana:
    image: grafana/grafana-oss:10.0.0
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hadesarchitect-cassandra-datasource
    volumes:
      - /var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/cassandra

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: mycluster
    volumes:
      - /var/lib/Cassandra